@if ($step === 'goal')
    <div class="assistant-message-row assistant-message-left"><div class="assistant-avatar">PK</div><div class="assistant-bubble assistant-bubble-support assistant-wide-bubble"><p class="assistant-speaker">Pace Keeper サポーター</p><h2 class="mt-2 text-xl font-bold text-slate-100">どのような目標を管理しますか？</h2><form method="POST" action="{{ route('chat.answer') }}" class="mt-4 space-y-4">@csrf<label><span class="form-label">計画名</span><input name="title" class="form-control" required value="{{ old('title') }}"></label><label><span class="form-label">概要</span><textarea name="description" rows="5" class="form-control">{{ old('description') }}</textarea></label><button type="submit" class="btn-primary">次へ</button></form></div></div>
@endif
@if ($step === 'category')
    <div class="assistant-message-row assistant-message-left"><div class="assistant-avatar">PK</div><div class="assistant-bubble assistant-bubble-support"><p class="assistant-speaker">Pace Keeper サポーター</p><h2 class="mt-2 text-xl font-bold text-slate-100">カテゴリを入力してください</h2><form method="POST" action="{{ route('chat.answer') }}" class="mt-4 space-y-4">@csrf<input name="category" class="form-control" placeholder="例：資格学習、ゲーム開発"><button type="submit" class="btn-primary">次へ</button></form></div></div>
@endif
@if ($step === 'dates')
    <div class="assistant-message-row assistant-message-left"><div class="assistant-avatar">PK</div><div class="assistant-bubble assistant-bubble-support"><p class="assistant-speaker">Pace Keeper サポーター</p><h2 class="mt-2 text-xl font-bold text-slate-100">期間を設定してください</h2><form method="POST" action="{{ route('chat.answer') }}" class="mt-4 grid gap-4 md:grid-cols-2">@csrf<label><span class="form-label">開始日</span><input type="date" name="start_date" class="form-control" value="{{ now()->toDateString() }}" required></label><label><span class="form-label">期限</span><input type="date" name="deadline" class="form-control" required></label><button type="submit" class="btn-primary md:col-span-2 md:w-fit">次へ</button></form></div></div>
@endif
@if ($step === 'visibility')
    <div class="assistant-message-row assistant-message-left"><div class="assistant-avatar">PK</div><div class="assistant-bubble assistant-bubble-support"><p class="assistant-speaker">Pace Keeper サポーター</p><h2 class="mt-2 text-xl font-bold text-slate-100">公開しますか？</h2><form method="POST" action="{{ route('chat.answer') }}" class="mt-4"><div class="chat-option-row">@csrf<label class="chat-option-pill"><input type="radio" name="is_public" value="0" required><span>非公開</span></label><label class="chat-option-pill"><input type="radio" name="is_public" value="1" required><span>公開</span></label></div><button type="submit" class="btn-primary mt-4">確認へ</button></form></div></div>
@endif
