@if ($step === 'plan')
    <div class="assistant-message-row assistant-message-left"><div class="assistant-avatar">PK</div><div class="assistant-bubble assistant-bubble-support assistant-wide-bubble"><h2 class="text-xl font-bold text-slate-100">追加先のPlanを選んでください</h2><form method="POST" action="{{ route('chat.answer') }}" class="mt-4 space-y-3">@csrf @foreach ($ownedPlans as $plan)<label class="chat-choice-card"><input type="radio" name="plan_id" value="{{ $plan->id }}" required><span class="font-bold text-slate-100">{{ $plan->title }}</span></label>@endforeach<button class="btn-primary">次へ</button></form></div></div>
@elseif ($step === 'details')
    <div class="assistant-message-row assistant-message-left"><div class="assistant-avatar">PK</div><div class="assistant-bubble assistant-bubble-support"><h2 class="text-xl font-bold text-slate-100">Taskの内容</h2><form method="POST" action="{{ route('chat.answer') }}" class="mt-4 space-y-4">@csrf<label><span class="form-label">Task名</span><input name="title" class="form-control" required></label><label><span class="form-label">達成条件・説明</span><textarea name="description" class="form-control" rows="3"></textarea></label><button class="btn-primary">次へ</button></form></div></div>
@elseif ($step === 'estimate')
    <div class="assistant-message-row assistant-message-left"><div class="assistant-avatar">PK</div><div class="assistant-bubble assistant-bubble-support"><h2 class="text-xl font-bold text-slate-100">想定時間</h2><form method="POST" action="{{ route('chat.answer') }}" class="mt-4 space-y-4">@csrf<select name="minutes_choice" class="form-control"><option value="30">30分</option><option value="60">1時間</option><option value="120">2時間</option><option value="240">4時間</option><option value="custom">その他</option></select><input type="number" name="custom_minutes" min="0" class="form-control" placeholder="その他の場合の分数"><button class="btn-primary">次へ</button></form></div></div>
@elseif ($step === 'settings')
    <div class="assistant-message-row assistant-message-left"><div class="assistant-avatar">PK</div><div class="assistant-bubble assistant-bubble-support"><h2 class="text-xl font-bold text-slate-100">優先度と開始ハードル</h2><form method="POST" action="{{ route('chat.answer') }}" class="mt-4 space-y-4">@csrf<label><span class="form-label">優先度（1が最優先）</span><input type="number" name="priority" min="1" max="5" value="3" class="form-control" required></label><label><span class="form-label">開始ハードル（1が最も始めやすい）</span><input type="number" name="activation_cost" min="1" max="5" value="3" class="form-control" required></label><button type="submit" class="btn-primary">確認へ</button></form></div></div>
@endif
